/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2016-05-29 20:50:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.pergunta;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cadastro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/yagot/Desktop/ClickTrauma/WebService/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ClickTrauma/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153395882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1461675125479L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<title>Cadastro de perguntas</title>\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<a href=\"lista\">Lista</a>\r\n");
      out.write("\t<br /> <br />\r\n");
      out.write("\t<form action=\"insere\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"pergunta\"><b>Pergunta:</b></label></td>\r\n");
      out.write("\t\t\t\t<td><textarea rows=\"2\" cols=\"30\" name=\"textoPerguntaPt\" id=\"pergunta\" required></textarea></td>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<td><label for=\"img-pergunta\">Imagem:</label></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"file\" id=\"img-pergunta\" name=\"img\"></td>\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t<td><label for=\"question\"><b>Question:</b></label></td>\r\n");
      out.write("\t\t\t\t<td><textarea rows=\"2\" cols=\"30\" name=\"textoPerguntaEn\" id=\"question\" required></textarea></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td></td>\t\r\n");
      out.write("\t\t\t\t<td>Correta</td>\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"resp1\">Resposta 1:</label></td>\r\n");
      out.write("\t\t\t\t<td><input name=\"textosRespostasPt[]\" id=\"resp1\" required></td>\r\n");
      out.write("\t\t\t\t<td><input name=\"respostas[0].correta\" type=\"checkbox\"></td>\t\t\t\t\r\n");
      out.write("\t\t\t\t<td><label for=\"img-resp-0\">Imagem:</label></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"file\" id=\"img-resp-0\" name=\"respostas[0].img\"></td>\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"ans1\">Answer 1:</label></td>\r\n");
      out.write("\t\t\t\t<td><input name=\"textosRespostasEn[]\" id=\"ans1\" required></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"resp2\">Resposta 2:</label></td>\r\n");
      out.write("\t\t\t\t<td><input name=\"textosRespostasPt[]\" id=\"resp2\" required></td>\r\n");
      out.write("\t\t\t\t<td><input name=\"respostas[1].correta\" type=\"checkbox\"></td>\t\t\t\t\r\n");
      out.write("\t\t\t\t<td><label for=\"img-resp-1\">Imagem:</label></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"file\" id=\"img-resp-1\" name=\"respostas[1].img\"></td>\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t<td><label for=\"ans2\">Answer 2:</label></td>\r\n");
      out.write("\t\t\t\t<td><input name=\"textosRespostasEn[]\" id=\"ans2\" required></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"resp3\">Resposta 3:</label></td>\r\n");
      out.write("\t\t\t\t<td><input name=\"textosRespostasPt[]\" id=\"resp3\" required></td>\r\n");
      out.write("\t\t\t\t<td><input name=\"respostas[2].correta\" type=\"checkbox\"></td>\t\t\r\n");
      out.write("\t\t\t\t<td><label for=\"img-resp-2\">Imagem:</label></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"file\" id=\"img-resp-2\" name=\"respostas[2].img\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t<td><label for=\"ans3\">Answer 3:</label></td>\r\n");
      out.write("\t\t\t\t<td><input name=\"textosRespostasEn[]\" id=\"ans3\" required></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"resp4\">Resposta 4:</label></td>\r\n");
      out.write("\t\t\t\t<td><input name=\"textosRespostasPt[]\" id=\"resp4\" required></td>\r\n");
      out.write("\t\t\t\t<td><input name=\"respostas[3].correta\" type=\"checkbox\"></td>\t\r\n");
      out.write("\t\t\t\t<td><label for=\"img-resp-3\">Imagem:</label></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"file\" id=\"img-resp-3\" name=\"respostas[3].img\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\t\t\t\r\n");
      out.write("\t\t\t\t<td><label for=\"ans4\">Answer 4:</label></td>\r\n");
      out.write("\t\t\t\t<td><input name=\"textosRespostasEn[]\" id=\"ans4\" required></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"resp5\">Resposta 5:</label></td>\r\n");
      out.write("\t\t\t\t<td><input name=\"textosRespostasPt[]\" id=\"resp5\"></td>\r\n");
      out.write("\t\t\t\t<td><input name=\"respostas[4].correta\" type=\"checkbox\"></td>\t\r\n");
      out.write("\t\t\t\t<td><label for=\"img-resp-4\">Imagem:</label></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"file\" id=\"img-resp-4\" name=\"respostas[4].img\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t<td><label for=\"ans5\">Answer 5:</label></td>\r\n");
      out.write("\t\t\t\t<td><input name=\"textosRespostasEn[]\" id=\"ans5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><button id=\"insere\">Insere</button></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/pergunta/cadastro.jsp(9,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty param.inserido}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t<script type=\"text/javascript\">\r\n");
        out.write("\t\t\talert(\"Pergunta cadastrada com sucesso.\");\t\t\r\n");
        out.write("\t\t</script>\r\n");
        out.write("\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
